

import type { Metadata } from "next";
import "./globals.css";
import AuthNavBar from '../components/AuthNavBar';
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="antialiased">
        <AuthNavBar />
        <main>
          {children}
        </main>
        
        <footer className="bg-gray-100 border-t">
          {/* Admin access - subtle link at the very bottom */}
          <div className="border-t border-gray-200 mt-8 pt-4">
            <div className="max-w-7xl mx-auto px-4 pb-4">
              <div className="flex justify-between items-center text-xs text-gray-400">
                <span>© 2024 Portal Home Hub</span>
                <Link 
                  href="/admin-login" 
                  className="hover:text-gray-600 transition-colors"
                >
                  Staff Access
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
